### ISSUE TITLE
what is generated when one runs

### ISSUE THREAD

**Issue by abitofalchemy** [chan150/TrillionG#2]
`bash run-local.sh output_file`?

**Comment by chan150** [comment]
The command "bash run.sh output_file" make a file, named output_file, with default parameters.
-p 0.57,0.19,0.19,0.05             # RMAT parameter used in graph500 (each quadrant a,b,c,and d respectively)
-n 20                                      # problem scale 20 (# of vertices = 2^20)
-r 16                                       # ratio between # of vertices and # of edges 
-noise 0.0                               # without adding a noise 
-format adj6                           # adjacency list format (binary representation with 6 byte alignment)

### adj6 representation (binary, to be used for the performance)
[src][degree_of_src][ adjacency list of src]
e.g.
$ hexdump part-00000 |head -n 5
0000000 0000 0000 0000 0000 0000 299b 0000 0000  
0000010 0000 0000 0400 8141 0000 0000 c100 0000
0000020 0e00 6812 0000 0400 3614 0000 0000 8201
0000030 0000 0400 64b0 0000 0500 5080 0000 0000
0000040 5908 0000 0000 5090 0000 0900 0001 0000

src = 0000 0000 0000, degree= 0000 0000 299b, 
list = 0000 0000 0000, 0400 8141 0000, 0000 c100 0000, 0e00 6812 0000, so on...

### recommendation ###
use the command "bash run.sh output_file -format tsv" instead of "bash run.sh output_file"

**Comment by chan150** [comment]
### TSV representation with Text ###
[src] [\t] [dest] [\n]
[src2] [\t] [dest2] [\n]
...

e.g.,
0      1
0      2
0      3
1      4
...
